#!/bin/bash
red="\033[1;31m"
color_end="\033[0m"

if [[ `git diff --cached --check` ]]; then
                  echo -e ${red}Commit failed${color_end}
                  git diff --cached --check
                  exit 1
fi
for FILE in $(git diff --cached --diff-filter=ACMTR --name-only HEAD | grep -E '\.xml|\.xsl');
do
            xmllint --noout $FILE
done
